### ISSUE TITLE
Try this code piece instead? :) v2

### ISSUE THREAD

**Issue by martindisch** [martindisch/gd32vf103-demo#1]
Ping @luojia65.

I accidentally deleted this repository instead of my HAL fork (that's why they make you type in the name, but that doesn't help if you just copy it without thinking :laughing:). I've been able to easily recreate the repo from my local checkout, but I did lose your original issue. I've recreated it just to tell you that I updated my example to use your new `Delay` in 0879ab58d24e16a5df3a6649ea48bfdc47a72e88. It's much nicer now. Thanks again!

**Comment by luojia65** [comment]
👍 Great
